# Test the testing framework is enabled and configured.
add_test(Test_Test arwain_test Test_Test)

# Test the quaternion library.
add_test(Test_QuatenrionConstructors arwain_test Test_QuaternionConstructors)
add_test(Test_QuaternionInverse arwain_test Test_QuaternionInverse)
add_test(Test_QuaternionSum arwain_test Test_QuaternionSum)
add_test(Test_QuaternionAxisAngleConstructor arwain_test Test_QuaternionAxisAngleConstructor)
add_test(Test_QuaternionDefaultConstructor arwain_test Test_QuaternionDefaultConstructor)
add_test(Test_QuaternionVectorConstructor arwain_test Test_QuaternionVectorConstructor)
add_test(Test_QuaternionDotProduct arwain_test Test_QuaternionDotProduct)
add_test(Test_QuaternionAngleBetween arwain_test Test_QuaternionAngleBetween)
add_test(Test_QuaternionSubtractionOperator arwain_test Test_QuaternionSubtractionOperator)
add_test(Test_Timer arwain_test Test_Timer)
add_test(Test_InputParser arwain_test Test_InputParser)
