#!/bin/bash

if [[ "$1" == "rock" ]]; then
  COMPILER=~/firefly/proj/firefly-sdk/buildroot/output/rockchip_rk1808/host/bin/aarch64-linux-g++
elif [[ "$1" == "pi" ]]; then
  COMPILER=g++
else
  echo "Choose a compiler by specifying pi or rock"
  exit
fi

# exit

cd src
echo "Building main"
$COMPILER \
    -o ../build/arwain \
        main.cpp \
        quaternions.cpp \
        stance.cpp \
        bmi2.c \
        bmi270.c \
        bmm150.c \
        imu_utils.cpp \
        utils.cpp \
        madgwick.cpp \
        efaroe.cpp \
        math_util.cpp \
        bin_log.cpp \
        input_parser.cpp \
    -std=c++17 \
    -Wall \
    -pthread \
    -lstdc++fs \
    -ldl \
    -li2c \
    && \
echo "Building calibrator"
$COMPILER \
    -o ../build/calibrate \
        calibrate_bmi270.cpp \
        bmi2.c \
        bmi270.c \
        imu_utils.cpp \
        bmm150.c \
    -std=c++17 \
    -Wall \
    -lstdc++fs \
    -li2c \
    && \
echo "Copying main executable to Rockchip"
scp ../build/main root@192.168.2.114:/root/main
