#!/bin/bash
cd src
echo "Building main"
~/firefly/proj/firefly-sdk/buildroot/output/rockchip_rk1808/host/bin/aarch64-linux-g++ -std=c++17 -o ../build/main main.cpp quaternions.cpp stance.cpp bmi2.c bmi270.c bmm150.c pi_utils.cpp utils.cpp madgwick.cpp math_util.cpp -pthread -lstdc++fs -L/home/colin/firefly/proj/firefly-sdk/buildroot/output/rockchip_rk1808/target/usr/lib -li2c -lrknn_api -lrknn_runtime -Wall
#echo "Building calibrator"
#g++ -std=c++17 -o ../build/calibrate calibrate_bmi270.cpp bmi2.c bmi270.c pi_utils.cpp bmm150.c -li2c -lstdc++fs -Wall
